Repository tudo-astroparticlephysics/PROPOSAL, pull requests merged in 2021-05, with the labels that each got.

#157 Use boost filesystem for backwards compability.
  .github/workflows/cpp.yml
  INSTALL.md
  README.md
  conanfile.py
  tests/Annihilation_TEST.cxx
  tests/Bremsstrahlung_TEST.cxx
  tests/CMakeLists.txt
  tests/Compton_TEST.cxx
  tests/ContinuousRandomization_TEST.cxx
  tests/DecayChannel_TEST.cxx
  tests/Epairproduction_TEST.cxx
  tests/Ionization_TEST.cxx
  tests/Mupairproduction_TEST.cxx
  tests/PROPOSALTestUtilities/TestFilesHandling.h
  tests/PhotoPair_TEST.cxx
  tests/Photonuclear_TEST.cxx
  tests/Scattering_TEST.cxx
  tests/Sector_TEST.cxx
  tests/WeakInteraction_TEST.cxx
Labels: build system, ready for merge

#155 Setup GitHub actions
  .github/workflows/cpp.yml
  .github/workflows/pypi_depoloy.yml
  .github/workflows/python.yml
  .travis.yml
  INSTALL.md
  README.md
  conanfile.py
  pyproject.toml
  tests/Annihilation_TEST.cxx
  tests/Bremsstrahlung_TEST.cxx
  tests/CMakeLists.txt
  tests/Compton_TEST.cxx
  tests/ContinuousRandomization_TEST.cxx
  tests/DecayChannel_TEST.cxx
  tests/Epairproduction_TEST.cxx
  tests/Ionization_TEST.cxx
  tests/Mupairproduction_TEST.cxx
  tests/PROPOSALTestUtilities/TestFilesHandling.h
  tests/PhotoPair_TEST.cxx
  tests/Photonuclear_TEST.cxx
  tests/Scattering_TEST.cxx
  tests/Sector_TEST.cxx
  tests/WeakInteraction_TEST.cxx
Labels: CI, ready for merge

#150 WIP: Find appropriate solution for visibility settings / Rework CMakeLists.txt
  CMakeLists.txt
Labels: build system, discussion

#177 Fix conversion of Vector3D types via consturctors in pybind11
  src/pyPROPOSAL/detail/pybindings.cxx
Labels: bug
