Repository tudo-astroparticlephysics/PROPOSAL, pull requests merged in 2022-03, with the labels that each got.

#267 Rewrite Propagator::AdvanceParticle method
  src/PROPOSAL/PROPOSAL/Propagator.h
  src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
Labels: bug

#265 Add γ->µµ as a new interaction process
  docs/config_docu.md
  src/PROPOSAL/PROPOSAL/PROPOSAL.h
  src/PROPOSAL/PROPOSAL/crosssection/Factories/PhotoMuPairProductionFactory.h
  src/PROPOSAL/PROPOSAL/crosssection/parametrization/PhotoMuPairProduction.h
  src/PROPOSAL/PROPOSAL/particle/Particle.h
  src/PROPOSAL/PROPOSAL/secondaries/parametrization/photomupairproduction/PhotoMuPairProduction.h
  src/PROPOSAL/PROPOSAL/secondaries/parametrization/photomupairproduction/PhotoMuPairProductionBurkhardtKelnerKokoulin.h
  src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
  src/PROPOSAL/detail/PROPOSAL/crosssection/Factories/PhotoMuPairProductionFactory.cxx
  src/PROPOSAL/detail/PROPOSAL/crosssection/parametrization/PhotoMuPairProduction.cxx
  src/PROPOSAL/detail/PROPOSAL/secondaries/parametrization/photomupairproduction/PhotoMuPairProductionBurkhardtKelnerKokoulin.cxx
  src/pyPROPOSAL/detail/crosssection.cxx
  src/pyPROPOSAL/detail/parametrization.cxx
  src/pyPROPOSAL/detail/particle.cxx
  src/pyPROPOSAL/detail/secondaries.cxx
  tests/SecondaryProduction_TEST.cxx
Labels: physics

#269 Add UnitTests for PhotoMuPairProduction
  src/PROPOSAL/PROPOSAL/crosssection/parametrization/Parametrization.hpp
  tests/CMakeLists.txt
  tests/PhotoMuPair_TEST.cxx
  tests/gen_testfiles_scripts/photomupair.py
Labels: CI

#244 Add deflection Van Ginneken
  src/PROPOSAL/PROPOSAL/PROPOSAL.h
  src/PROPOSAL/PROPOSAL/propagation_utility/PropagationUtility.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/Parametrization.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/ScatteringFactory.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsGinneken.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsTsaiApproximation.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/epairproduction/EpairGinneken.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/epairproduction/EpairProduction.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/ionization/IonizNaive.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/photonuclear/PhotoBorogPetrukhin.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/photonuclear/PhotoGinneken.h
  src/PROPOSAL/PROPOSAL/scattering/stochastic_deflection/photonuclear/Photonuclear.h
  src/PROPOSAL/detail/PROPOSAL/Propagator.cxx
  src/PROPOSAL/detail/PROPOSAL/propagation_utility/PropagationUtility.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsGinneken.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/bremsstrahlung/BremsTsaiApproximation.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/epairproduction/EpairGinneken.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/ionization/IonizNaive.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/photonuclear/PhotoBorogPetrukhin.cxx
  src/PROPOSAL/detail/PROPOSAL/scattering/stochastic_deflection/photonuclear/PhotoGinneken.cxx
  src/pyPROPOSAL/detail/scattering.cxx
Labels: enhancement, physics
